Repository kumodao/kumo-protocol, pull requests merged in 2022-08, with the labels that each got.

#174 Upgraded eslint to 8.20.0, with dependant upgrades eslint-plugin and …
  packages/dev-frontend/src/App.test.tsx
  packages/lib-base/package.json
  packages/lib-ethers/package.json
  packages/lib-react/package.json
  yarn.lock
Labels: dependencies

#182 add BOOTSTRAP_PERSIOD to KumoParameters
  packages/contracts/contracts/Interfaces/IKumoParameters.sol
  packages/contracts/contracts/KumoParameters.sol
  packages/contracts/contracts/TroveManager.sol
Labels: bug

#185 removed migrations.sol contract
  packages/contracts/contracts/Migrations.sol
Labels: smart-contract

#231 UUPS SortedTroves
  .github/workflows/test-contracts.yml
  packages/contracts/contracts/SortedTroves.sol
  packages/contracts/contracts/V2/SortedTrovesV2.sol
  packages/contracts/hardhat.config.js
  packages/contracts/package.json
  packages/contracts/test/AccessControlTest.js
  packages/contracts/test/OwnershipTest.js
  packages/contracts/test/SortedTrovesTest.js
  packages/contracts/utils/deploymentHelpers.js
  yarn.lock
Labels: upgradability

#232 Best Practise: Fix TroveManagerTests with asset parameter
  packages/contracts/contracts/ActivePool.sol
  packages/contracts/contracts/BorrowerOperations.sol
  packages/contracts/contracts/CollSurplusPool.sol
  packages/contracts/contracts/DefaultPool.sol
  packages/contracts/contracts/Dependencies/SafetyTransfer.sol
  packages/contracts/contracts/Interfaces/IActivePool.sol
  packages/contracts/contracts/Interfaces/ICollSurplusPool.sol
  packages/contracts/contracts/Interfaces/IKUMOStaking.sol
  packages/contracts/contracts/Interfaces/IKUMOToken.sol
  packages/contracts/contracts/Interfaces/IKumoParameters.sol
  packages/contracts/contracts/Interfaces/ISortedTroves.sol
  packages/contracts/contracts/Interfaces/ITroveManager.sol
  packages/contracts/contracts/KUMO/KUMOStaking.sol
  packages/contracts/contracts/KUMO/KUMOToken.sol
  packages/contracts/contracts/KumoParameters.sol
  packages/contracts/contracts/Proxy/BorrowerWrappersScript.sol
  packages/contracts/contracts/SortedTroves.sol
  packages/contracts/contracts/StabilityPoolManager.sol
  packages/contracts/contracts/TestContracts/ActivePoolTester.sol
  packages/contracts/contracts/TestContracts/ERC20Test.sol
  packages/contracts/contracts/TestContracts/EchidnaTester.sol
  packages/contracts/contracts/TroveManager.sol
  packages/contracts/test/TroveManagerTest.js
  packages/contracts/utils/deploymentHelpers.js
  packages/contracts/utils/testHelpers.js
  packages/lib-ethers/abi/ActivePool.json
  packages/lib-ethers/abi/CollSurplusPool.json
  packages/lib-ethers/abi/DefaultPool.json
  packages/lib-ethers/abi/KUMOStaking.json
  packages/lib-ethers/abi/KumoParameters.json
  packages/lib-ethers/abi/SortedTroves.json
  packages/lib-ethers/abi/TroveManager.json
  packages/lib-ethers/types/index.ts
  packages/subgraph/subgraph.yaml.js
Labels: multi-asset

#236 227 fix all tests in trovemanager liquidationrewardstestjs related to the multi asset feature
  packages/contracts/contracts/BorrowerOperations.sol
  packages/contracts/test/TroveManagerTest.js
  packages/contracts/test/TroveManager_LiquidationRewardsTest.js
  packages/contracts/utils/testHelpers.js
Labels: ci/cd, multi-asset
